In [2]:
import torch

In [3]:
def compute_z(a, b, c):
    r1 = torch.sub(a, b)
    r2 = torch.mul(r1, 2)
    z = torch.add(r2, c)
    return z

In [13]:
print ('Scalar input:', compute_z(torch.tensor(1), 
      torch.tensor(2), torch.tensor(100)))

Scalar input: tensor(98)


In [10]:
a = torch.tensor(1)

In [12]:
print(a)

tensor(1)


In [18]:
a = torch.tensor(3.14, requires_grad=True)

In [19]:
print(a)

tensor(3.1400, requires_grad=True)


In [20]:
w = torch.tensor([1.0, 2.0, 3.0])

In [21]:
print(w.requires_grad)

False


In [23]:
w.requires_grad_()

tensor([1., 2., 3.], requires_grad=True)

In [24]:
print(w.requires_grad)

True


In [25]:
import torch.nn as nn
torch.manual_seed(1)
w = torch.empty(2, 3)
nn.init.xavier_normal_(w)

tensor([[ 0.4183,  0.1688,  0.0390],
        [ 0.3930, -0.2858, -0.1051]])

In [26]:
print(w)

tensor([[ 0.4183,  0.1688,  0.0390],
        [ 0.3930, -0.2858, -0.1051]])


In [27]:
class MyModule(nn.Module):
    def __init__(self):
        super().__init__()
        self.w1 = torch.empty(2, 3, requires_grad = True)
        nn.init.xavier_normal_(self.w1)
        self.w2 = torch.empty(1, 2, requires_grad = True)
        nn.init.xavier_normal_(self.w2)