<a href="https://colab.research.google.com/github/jaeohshin/ML_with_Pytorch_Sklearn_rasbt/blob/main/ch18_GNN.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import networkx as nx
G = nx.Graph()

In [5]:
blue, orange, green = "#1f77b4", "#ff7f0e", "#2ca02c"
G.add_nodes_from([
    (1, {"color": blue}),
    (2, {"color": orange}),
    (3, {"color": blue}),
    (4, {"color": green})
])

In [6]:
G.add_edges_from([(1, 2), (2, 3), (1, 3), (3, 4)])

In [7]:
A = np.asarray(nx.adjacency_matrix(G).todense())

In [8]:
print(A)

[[0 1 1 0]
 [1 0 1 0]
 [1 1 0 1]
 [0 0 1 0]]


In [ ]:
def build_graph_color_label_representation(G, mapping_dict):
    one_hot_idxs = np.array