<a href="https://colab.research.google.com/github/jaeohshin/ML_with_Pytorch_Sklearn_rasbt/blob/main/pytorch_blitz.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import torch
import numpy as np

In [3]:
data = [[1, 2], [3,4]]
x_data = torch.tensor(data)

In [11]:
np_array = np.array(data)
x_np = torch.from_numpy(np_array)

In [10]:
print(np_array)

[[1 2]
 [3 4]]


In [12]:
print(x_np)

tensor([[1, 2],
        [3, 4]])


In [13]:
x_ones = torch.ones_like(x_data)

In [14]:
print(x_ones)

tensor([[1, 1],
        [1, 1]])


In [21]:
x_rand = torch.rand_like(x_data, dtype=torch.float)
print(f"Random Tensor: \n {x_rand} \n")

Random Tensor: 
 tensor([[0.4309, 0.8886],
        [0.3557, 0.9924]]) 



In [25]:
shape = (2, 3, )
rand_tensor = torch.rand(shape)
print(f'rand_tensor: \n {rand_tensor}\n')

rand_tensor: 
 tensor([[0.6858, 0.0797, 0.7663],
        [0.2816, 0.3379, 0.9092]])



In [26]:
shape = (2, 3)
rand_tensor = torch.rand(shape)
print(f'rand_tensor: \n {rand_tensor}\n')

rand_tensor: 
 tensor([[0.1692, 0.4771, 0.3519],
        [0.3433, 0.9042, 0.7355]])



In [27]:
tensor = torch.rand(3, 4)

In [29]:
print(f"Shape of tensor: {tensor.shape}")
print(f"Datatype of tensor: {tensor.dtype}")
print(f"Device tensor is stored on: {tensor.device}")

Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


In [30]:
if torch.cuda.is_available():
    tensor = tensor.to('cuda')
    print(f"Device tensor is stored on: {tensor.device}")

Device tensor is stored on: cuda:0


In [36]:
tensor = torch.ones(4, 4, )
print(tensor)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])


In [37]:
tensor[:, 1]=0
print(tensor)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


In [40]:
t1 = torch.cat([tensor, tensor, tensor], dim=1)
print(t1)

tensor([[1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.]])
