In [1]:
import torch
import numpy as np


In [2]:
a = [1 ,2, 3]
t_a = torch.tensor(a)

In [3]:
print(t_a)

tensor([1, 2, 3])


In [4]:
print(t_a.dtype)

torch.int64


In [5]:
t_a_new = t_a.to(torch.int32)

In [6]:
print(t_a_new.dtype)

torch.int32


In [7]:
t = torch.rand(3, 5)

In [8]:
t

tensor([[0.7197, 0.6321, 0.5873, 0.8324, 0.0059],
        [0.4989, 0.5018, 0.3465, 0.6324, 0.7594],
        [0.9163, 0.9777, 0.5969, 0.0400, 0.4953]])

In [9]:
print(t)

tensor([[0.7197, 0.6321, 0.5873, 0.8324, 0.0059],
        [0.4989, 0.5018, 0.3465, 0.6324, 0.7594],
        [0.9163, 0.9777, 0.5969, 0.0400, 0.4953]])


In [10]:
t_tr = torch.transpose(t, 0, 1)

In [11]:
t_tr

tensor([[0.7197, 0.4989, 0.9163],
        [0.6321, 0.5018, 0.9777],
        [0.5873, 0.3465, 0.5969],
        [0.8324, 0.6324, 0.0400],
        [0.0059, 0.7594, 0.4953]])

In [12]:
t

tensor([[0.7197, 0.6321, 0.5873, 0.8324, 0.0059],
        [0.4989, 0.5018, 0.3465, 0.6324, 0.7594],
        [0.9163, 0.9777, 0.5969, 0.0400, 0.4953]])

In [13]:
print(t.shape)

torch.Size([3, 5])


In [14]:
print(t_tr.shape)

torch.Size([5, 3])


In [15]:
t= torch.zeros(30)

In [16]:
t

tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0.])

In [17]:
t_reshape = t.reshape(2, 5, 3)

In [18]:
t_reshape

tensor([[[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]]])

In [19]:
t = torch.rand(2, 3, 1)

In [20]:
t

tensor([[[0.8168],
         [0.3300],
         [0.9124]],

        [[0.1275],
         [0.2054],
         [0.4098]]])

In [21]:
print(t.shape)

torch.Size([2, 3, 1])


In [22]:
t_sqz = torch.squeeze(t, 2)

In [23]:
t_sqz

tensor([[0.8168, 0.3300, 0.9124],
        [0.1275, 0.2054, 0.4098]])

In [24]:
torch.manual_seed(1)

In [25]:
t1 = 2 * torch.rand(5, 2) - 1
t2 = torch.normal(mean=0, std=1, size=(5, 2))

In [26]:
t1

tensor([[ 0.5153, -0.4414],
        [-0.1939,  0.4694],
        [-0.9414,  0.5997],
        [-0.2057,  0.5087],
        [ 0.1390, -0.1224]])

In [27]:
t2

tensor([[ 0.8590,  0.7056],
        [-0.3406, -1.2720],
        [-1.1948,  0.0250],
        [-0.7627,  1.3969],
        [-0.3245,  0.2879]])

In [28]:
t3 = torch.multiply(t1, t2)

In [29]:
t3

tensor([[ 0.4426, -0.3114],
        [ 0.0660, -0.5970],
        [ 1.1249,  0.0150],
        [ 0.1569,  0.7107],
        [-0.0451, -0.0352]])

In [30]:
t4 = torch.mean(t1, axis=1)

In [31]:
print(t4)

tensor([ 0.0369,  0.1378, -0.1709,  0.1515,  0.0083])


In [32]:
print(torch.sum(t1, axis=1))

tensor([ 0.0739,  0.2755, -0.3417,  0.3030,  0.0166])


In [33]:
t5 = torch.matmul(t1, torch.transpose(t2, 0, 1))

In [34]:
print(t5)

tensor([[ 0.1312,  0.3860, -0.6267, -1.0096, -0.2943],
        [ 0.1647, -0.5310,  0.2434,  0.8035,  0.1980],
        [-0.3855, -0.4422,  1.1399,  1.5558,  0.4781],
        [ 0.1822, -0.5771,  0.2585,  0.8676,  0.2132],
        [ 0.0330,  0.1084, -0.1692, -0.2771, -0.0804]])


In [35]:
norm_t1 = torch.linalg.norm(t1, ord=1, dim=1)
print(norm_t1)

tensor([0.9566, 0.6632, 1.5412, 0.7145, 0.2615])


In [36]:
torch.manual_seed(1)

In [37]:
t= torch.rand(7)

In [38]:
t

tensor([0.7576, 0.2793, 0.4031, 0.7347, 0.0293, 0.7999, 0.3971])

In [39]:
t_splits = torch.chunk(t, 2)

In [40]:
print(t_splits)

(tensor([0.7576, 0.2793, 0.4031, 0.7347]), tensor([0.0293, 0.7999, 0.3971]))


In [41]:
torch.manual_seed(1)

In [42]:
t = torch.rand(5)

In [43]:
t_splits = torch.split(t, split_size_or_sections=[5, 0])

In [44]:
t_splits

(tensor([0.7576, 0.2793, 0.4031, 0.7347, 0.0293]), tensor([]))

In [45]:
A = torch.ones(3)
B = torch.zeros(3)
S = torch.stack([A, B], axis=0)

In [46]:
print(S)

tensor([[1., 1., 1.],
        [0., 0., 0.]])


## 12.3 파이토치 입력 파이프라인 구축

In [60]:
from torch.utils.data import DataLoader
t = torch.arange(8, dtype=torch.float32)

In [48]:
data_loader = DataLoader(t)

In [54]:
for item in data_loader:
    print(item)

tensor([0.])
tensor([1.])
tensor([2.])
tensor([3.])
tensor([4.])
tensor([5.])


In [67]:
data_loader = DataLoader(t, batch_size=5, drop_last=False)
for i, batch in enumerate(data_loader, 1):
    print(f'배치 {i}:', batch)

배치 1: tensor([0., 1., 2., 3., 4.])
배치 2: tensor([5., 6., 7.])


In [68]:
torch.manual_seed(1)
t_x = torch.rand([4, 3], dtype=torch.float32)
t_y = torch.arange(4)

In [69]:
t_x

tensor([[0.7576, 0.2793, 0.4031],
        [0.7347, 0.0293, 0.7999],
        [0.3971, 0.7544, 0.5695],
        [0.4388, 0.6387, 0.5247]])

In [70]:
t_y

tensor([0, 1, 2, 3])

In [71]:
from torch.utils.data import Dataset

In [79]:
class JointDataset(Dataset):
    def __init__(self, x, y):
        self.x = x
        self.y = y
    
    def __len__(self):
        return len(self.x)
    
    def __getitem__(self, idx):
        return self.x[idx], self.y[idx]

### special (dunder) methods
### __len__:
### __getitem__
### __setitem__
### __iter__
### __contains__
### __eq__
### __repr__
### __add__
### __sub__
### __call__
### ___del__
Summary of Common Special Methods:
Container Behavior: __len__, __getitem__, __setitem__, __contains__
Iteration: __iter__
Comparison: __eq__, __lt__, __gt__, etc.
Arithmetic: __add__, __sub__, __mul__, etc.
String Representation: __repr__, __str__
Callable: __call__
Context Manager: __enter__, __exit__

In [75]:
joint_dataset = JointDataset(t_x, t_y)

In [80]:
len(joint_dataset)

4

In [81]:
print(dir(JointDataset))

['__add__', '__annotations__', '__class__', '__class_getitem__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__getitem__', '__getstate__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__orig_bases__', '__parameters__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__slots__', '__str__', '__subclasshook__', '__weakref__', '_is_protocol']


In [82]:
for example in joint_dataset:
    print('x: ', example[0], 'y: ', example[1])

x:  tensor([0.7576, 0.2793, 0.4031]) y:  tensor(0)
x:  tensor([0.7347, 0.0293, 0.7999]) y:  tensor(1)
x:  tensor([0.3971, 0.7544, 0.5695]) y:  tensor(2)
x:  tensor([0.4388, 0.6387, 0.5247]) y:  tensor(3)


In [83]:
from torch.utils.data import TensorDataset
j_dataset = TensorDataset(t_x, t_y)

In [86]:
for example in j_dataset:
    print('x: ', example[0], 'y: ', example[1])

x:  tensor([0.7576, 0.2793, 0.4031]) y:  tensor(0)
x:  tensor([0.7347, 0.0293, 0.7999]) y:  tensor(1)
x:  tensor([0.3971, 0.7544, 0.5695]) y:  tensor(2)
x:  tensor([0.4388, 0.6387, 0.5247]) y:  tensor(3)


In [94]:
import torch
from torch.utils.data import TensorDataset, DataLoader

# Sample data
x = torch.tensor([[1.0, 2.0], [3.0, 4.0], [5.0, 6.0], [7.4, 9.9]])  # 3 data points, 2 features each
y = torch.tensor([0, 1, -1, 2])  # 3 labels corresponding to the data points

# Create TensorDataset
dataset = TensorDataset(x, y)

# Create a DataLoader to load the data in batches
data_loader = DataLoader(dataset, batch_size=3, shuffle=True)

# Iterate through the DataLoader
for batch_x, batch_y in data_loader:
    print(batch_x, batch_y)

tensor([[7.4000, 9.9000],
        [1.0000, 2.0000],
        [3.0000, 4.0000]]) tensor([2, 0, 1])
tensor([[5., 6.]]) tensor([-1])
