In [1]:
import torch
import numpy as np


In [2]:
a = [1 ,2, 3]
t_a = torch.tensor(a)

In [3]:
print(t_a)

tensor([1, 2, 3])


In [4]:
print(t_a.dtype)

torch.int64


In [5]:
t_a_new = t_a.to(torch.int32)

In [6]:
print(t_a_new.dtype)

torch.int32


In [7]:
t = torch.rand(3, 5)

In [8]:
t

tensor([[0.2764, 0.8433, 0.5552, 0.1104, 0.3780],
        [0.0521, 0.2773, 0.0193, 0.9593, 0.3177],
        [0.9776, 0.1460, 0.8786, 0.9234, 0.2442]])

In [9]:
print(t)

tensor([[0.2764, 0.8433, 0.5552, 0.1104, 0.3780],
        [0.0521, 0.2773, 0.0193, 0.9593, 0.3177],
        [0.9776, 0.1460, 0.8786, 0.9234, 0.2442]])


In [10]:
t_tr = torch.transpose(t, 0, 1)

In [11]:
t_tr

tensor([[0.2764, 0.0521, 0.9776],
        [0.8433, 0.2773, 0.1460],
        [0.5552, 0.0193, 0.8786],
        [0.1104, 0.9593, 0.9234],
        [0.3780, 0.3177, 0.2442]])

In [12]:
t

tensor([[0.2764, 0.8433, 0.5552, 0.1104, 0.3780],
        [0.0521, 0.2773, 0.0193, 0.9593, 0.3177],
        [0.9776, 0.1460, 0.8786, 0.9234, 0.2442]])

In [13]:
print(t.shape)

torch.Size([3, 5])


In [14]:
print(t_tr.shape)

torch.Size([5, 3])


In [15]:
t= torch.zeros(30)

In [16]:
t

tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0.])

In [17]:
t_reshape = t.reshape(2, 5, 3)

In [18]:
t_reshape

tensor([[[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]]])

In [19]:
t = torch.rand(2, 3, 1)

In [20]:
t

tensor([[[0.6326],
         [0.9068],
         [0.5899]],

        [[0.7808],
         [0.9750],
         [0.1497]]])

In [21]:
print(t.shape)

torch.Size([2, 3, 1])


In [22]:
t_sqz = torch.squeeze(t, 2)

In [23]:
t_sqz

tensor([[0.6326, 0.9068, 0.5899],
        [0.7808, 0.9750, 0.1497]])

In [24]:
torch.manual_seed(1)

In [25]:
t1 = 2 * torch.rand(5, 2) - 1
t2 = torch.normal(mean=0, std=1, size=(5, 2))

In [27]:
t1

tensor([[ 0.5153, -0.4414],
        [-0.1939,  0.4694],
        [-0.9414,  0.5997],
        [-0.2057,  0.5087],
        [ 0.1390, -0.1224]])

In [28]:
t2

tensor([[ 0.8590,  0.7056],
        [-0.3406, -1.2720],
        [-1.1948,  0.0250],
        [-0.7627,  1.3969],
        [-0.3245,  0.2879]])

In [29]:
t3 = torch.multiply(t1, t2)

In [30]:
t3

tensor([[ 0.4426, -0.3114],
        [ 0.0660, -0.5970],
        [ 1.1249,  0.0150],
        [ 0.1569,  0.7107],
        [-0.0451, -0.0352]])

In [33]:
t4 = torch.mean(t1, axis=1)

In [34]:
print(t4)

tensor([ 0.0369,  0.1378, -0.1709,  0.1515,  0.0083])


In [35]:
print(torch.sum(t1, axis=1))

tensor([ 0.0739,  0.2755, -0.3417,  0.3030,  0.0166])


In [36]:
t5 = torch.matmul(t1, torch.transpose(t2, 0, 1))

In [37]:
print(t5)

tensor([[ 0.1312,  0.3860, -0.6267, -1.0096, -0.2943],
        [ 0.1647, -0.5310,  0.2434,  0.8035,  0.1980],
        [-0.3855, -0.4422,  1.1399,  1.5558,  0.4781],
        [ 0.1822, -0.5771,  0.2585,  0.8676,  0.2132],
        [ 0.0330,  0.1084, -0.1692, -0.2771, -0.0804]])


In [42]:
norm_t1 = torch.linalg.norm(t1, ord=1, dim=1)
print(norm_t1)

tensor([0.9566, 0.6632, 1.5412, 0.7145, 0.2615])


In [50]:
torch.manual_seed(1)

In [57]:
t= torch.rand(7)

In [67]:
t

tensor([0.3971, 0.7544, 0.5695, 0.4388, 0.6387, 0.5247, 0.6826])

In [59]:
t_splits = torch.chunk(t, 2)

In [60]:
print(t_splits)

(tensor([0.3971, 0.7544, 0.5695, 0.4388]), tensor([0.6387, 0.5247, 0.6826]))


In [69]:
torch.manual_seed(1)

In [70]:
t = torch.rand(5)

In [73]:
t_splits = torch.split(t, split_size_or_sections=[5, 0])

In [74]:
t_splits

(tensor([0.7576, 0.2793, 0.4031, 0.7347, 0.0293]), tensor([]))